services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: EcommerceInventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: godika
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ecommerce-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: ecommerce-migrator
    working_dir: /src
    volumes:
      - ./:/src
    networks:
      - ecommerce-network
    environment:
      - POSTGRE_HOST=postgres
      - POSTGRE_PORT=5432
      - POSTGRE_DB=EcommerceInventory
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=godika
      - PATH=/root/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "=== Installing dotnet-ef tool ===" && \
        dotnet tool install --global dotnet-ef --version 8.0.* && \
        echo "=== Restoring packages ===" && \
        dotnet restore EcommerceInventory.Api/EcommerceInventory.Api.csproj && \
        echo "=== Running migrations ===" && \
        dotnet ef database update --project EcommerceInventory.Infrastructure/EcommerceInventory.Infrastructure.csproj --startup-project EcommerceInventory.Api/EcommerceInventory.Api.csproj --verbose && \
        echo "=== Migrations completed successfully ==="
    restart: "no"

  api:
    build:
      context: .
      dockerfile: EcommerceInventory.Api/Dockerfile
    container_name: ecommerce-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - POSTGRE_HOST=postgres
      - POSTGRE_PORT=5432
      - POSTGRE_DB=EcommerceInventory
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=godika
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Exchange=loyalty-events
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - ecommerce-network
    restart: on-failure

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data: